"""[api Design](/architecture/services/api.md#design) (OpenAPI): the served document equals the
committed snapshot `apps/api/openapi.json`, regenerated by `uv run poe openapi-snapshot`
whenever a contract changes."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi import FastAPI

pytestmark = pytest.mark.contract

SNAPSHOT_PATH = Path(__file__).resolve().parents[2] / "openapi.json"


async def test_served_openapi_document_equals_the_committed_snapshot(app: FastAPI) -> None:
    served = app.openapi()
    committed = json.loads(SNAPSHOT_PATH.read_text())
    assert served == committed
