/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/services/{id}/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API-39. */
        get: operations["list_prospects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/scores/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API-40. 404 when the account has no score for the service yet. */
        get: operations["get_score"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API-42. */
        get: operations["list_findings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API-43. */
        get: operations["get_evidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/scores/{service_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description API-44. Admin only. */
        post: operations["add_override"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overrides/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description API-45. Admin only. */
        post: operations["revoke_override"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        Band: "HOT" | "WARM" | "COLD";
        CrmSyncView: {
            id: string;
            external_id: string | null;
            error: string | null;
            created_at: string;
            /** @enum {unknown} */
            target: "HUBSPOT";
            /** @enum {unknown} */
            status: "SUCCEEDED" | "FAILED";
        };
        /**
         * DocumentSourceType
         * @description `document.source_type`.
         * @enum {string}
         */
        DocumentSourceType: "NEWS" | "COMPANY_PUBLICATION" | "JOB_POSTING" | "COMPANY_PROFILE";
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: {
                    fields?: {
                        field: string;
                        message: string;
                    }[];
                    /** Format: uuid */
                    entity_id?: string;
                    retry_after_min?: number;
                    /** Format: date-time */
                    resets_at?: string;
                    /** @enum {string} */
                    dependency?: "DATABASE" | "CLASSIFIER" | "LLM" | "EMBEDDER" | "HUBSPOT";
                    reason?: string;
                };
            };
        };
        EvidenceView: {
            finding_id: string;
            document: components["schemas"]["FindingViewDocument"];
            section: string | null;
            purged: boolean;
            excerpt: string | null;
            quote_start: number | null;
            quote_end: number | null;
        };
        /**
         * FindingDecidedBy
         * @description `finding.decided_by`.
         * @enum {string}
         */
        FindingDecidedBy: "CLASSIFIER" | "LLM";
        /**
         * FindingFeedbackVerdict
         * @description `finding_feedback.verdict`.
         * @enum {string}
         */
        FindingFeedbackVerdict: "CORRECT" | "WRONG";
        /**
         * FindingStatus
         * @description `finding.status`.
         * @enum {string}
         */
        FindingStatus: "ACTIVE" | "SUPERSEDED" | "REJECTED";
        /**
         * FindingStrength
         * @description `finding.strength`; reused by `classification.strength` and
         *     `evaluation_item.expected_strength`.
         * @enum {string}
         */
        FindingStrength: "NONE" | "WEAK" | "MEDIUM" | "STRONG";
        /**
         * FindingView
         * @description [`FindingView`](/architecture/interfaces.md#findingview), the response of `API-47`. Also
         *     plan task 13's `API-42` response shape; that task imports this model and must not define a
         *     second one.
         */
        FindingView: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Confidence */
            confidence: number;
            decided_by: components["schemas"]["FindingDecidedBy"];
            document: components["schemas"]["FindingViewDocument"];
            feedback: components["schemas"]["FindingViewFeedback"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            option: components["schemas"]["FindingViewOption"] | null;
            /** Points */
            points: number | null;
            question: components["schemas"]["FindingViewQuestion"];
            /** Question Revision */
            question_revision: number;
            /** Quote */
            quote: string;
            /** Quote En */
            quote_en: string | null;
            /** Rationale */
            rationale: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            status: components["schemas"]["FindingStatus"];
            strength: components["schemas"]["FindingStrength"];
        };
        /**
         * FindingViewDocument
         * @description `FindingView.document`.
         */
        FindingViewDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language: string;
            plugin_code: components["schemas"]["SourcePluginCode"];
            /** Published At */
            published_at: string | null;
            source_type: components["schemas"]["DocumentSourceType"];
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /**
         * FindingViewFeedback
         * @description `FindingView.feedback`: the in-force [`finding_feedback`]
         *     (/architecture/sql-store.md#finding_feedback).
         */
        FindingViewFeedback: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User Name */
            user_name: string;
            verdict: components["schemas"]["FindingFeedbackVerdict"];
        };
        /**
         * FindingViewOption
         * @description `FindingView.option`; `CHOICE` questions only.
         */
        FindingViewOption: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /**
         * FindingViewQuestion
         * @description `FindingView.question`.
         */
        FindingViewQuestion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            polarity: components["schemas"]["SignalQuestionPolarity"];
            /** Text */
            text: string;
        };
        /**
         * ICPCriterionKind
         * @description The `kind` of an ICP criterion of the [scoring settings document]
         *     (/architecture/sql-store.md#scoring-settings-document).
         * @enum {string}
         */
        ICPCriterionKind: "INDUSTRY" | "GEOGRAPHY" | "EMPLOYEE_RANGE" | "REVENUE_RANGE" | "OPERATIONAL_COMPLEXITY";
        /**
         * LeadFeedback
         * @description [`LeadFeedback`](/architecture/interfaces.md#leadfeedback), the response of `API-46`.
         */
        LeadFeedback: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /** User Name */
            user_name: string;
            verdict: components["schemas"]["LeadFeedbackVerdict"];
        };
        /**
         * LeadFeedbackVerdict
         * @description `lead_feedback.verdict`.
         * @enum {string}
         */
        LeadFeedbackVerdict: "RELEVANT" | "NOT_RELEVANT" | "ALREADY_CUSTOMER";
        Override: {
            id: string;
            account_id: string;
            service_id: string;
            rule_key: string;
            note: string;
            rule_label: string;
            status: components["schemas"]["OverrideStatus"];
            created_by_name: string;
            created_at: string;
            revoked_by_name: string | null;
            revoked_at: string | null;
            run_id: string | null;
        };
        OverrideCreate: {
            rule_key: string;
            note: string;
        };
        /** @enum {unknown} */
        OverrideStatus: "ACTIVE" | "REVOKED";
        ProspectPage: {
            items: components["schemas"]["ProspectRow"][];
            page: number;
            page_size: number;
            total: number;
            band_counts: {
                [key: string]: number;
            };
        };
        ProspectRow: {
            rank: number | null;
            account: {
                id: string;
                name: string;
                domain: string;
                country_code: string | null;
                industry: string | null;
            };
            fit: number;
            intent: number;
            priority: number;
            standing: components["schemas"]["Standing"];
            band: components["schemas"]["Band"] | null;
            reason: {
                min_fit: number | null;
                disqualifier_labels: string[] | null;
                customer_marked_by_name: string | null;
            } | null;
            top_signals: {
                question_key: string;
                question_text: string;
                strength: components["schemas"]["FindingStrength"];
                observed_at: string;
            }[];
            finding_count: number;
            unread_alerts: number;
            as_of: string;
            last_refreshed_at: string | null;
        };
        ScoreBreakdown: {
            settings_version: number;
            as_of: string;
            fit: {
                value: number;
                criteria: {
                    key: string;
                    kind: components["schemas"]["ICPCriterionKind"];
                    weight: components["schemas"]["WeightLevel"];
                    weight_value: number;
                    attribute: string | number | null;
                    /** @enum {unknown} */
                    match: "MATCH" | "MISMATCH" | "UNKNOWN";
                    credit: number;
                    points: number;
                }[];
            };
            intent: {
                value: number;
                positive_sum: number;
                negative_sum: number;
                max_positive: number;
                questions: {
                    question_key: string;
                    question_text: string;
                    polarity: components["schemas"]["SignalQuestionPolarity"];
                    weight: components["schemas"]["WeightLevel"];
                    weight_value: number;
                    finding_id: string | null;
                    strength: components["schemas"]["FindingStrength"] | null;
                    decay: number | null;
                    observed_at: string | null;
                    value: number;
                    points: number;
                }[];
            };
            disqualifiers: {
                key: string;
                label: string;
                /** @enum {unknown} */
                kind: "ICP_MISMATCH" | "SIGNAL";
                criterion_key: string | null;
                question_key: string | null;
                matched: boolean;
                overridden: boolean;
                override_id: string | null;
                finding_id: string | null;
            }[];
            priority: number;
            standing: components["schemas"]["Standing"];
            band: components["schemas"]["Band"] | null;
        };
        ScoreView: {
            score_id: string;
            account_id: string;
            service_id: string;
            scoring_version: number;
            as_of: string;
            fit: number;
            intent: number;
            priority: number;
            standing: components["schemas"]["Standing"];
            band: components["schemas"]["Band"] | null;
            rank: number | null;
            breakdown: components["schemas"]["ScoreBreakdown"];
            overrides: components["schemas"]["Override"][];
            lead_feedback: components["schemas"]["LeadFeedback"] | null;
            last_crm_sync: components["schemas"]["CrmSyncView"] | null;
        };
        /**
         * SignalQuestionPolarity
         * @description `signal_question.polarity`.
         * @enum {string}
         */
        SignalQuestionPolarity: "POSITIVE" | "NEGATIVE";
        /**
         * SourcePluginCode
         * @description `source_plugin.code`; reused by `plugin_usage.plugin_code` and `document.plugin_code`.
         * @enum {string}
         */
        SourcePluginCode: "GDELT" | "RSS" | "WEBSITE" | "CAREERS" | "CRUNCHBASE" | "NEWSAPI" | "SERPAPI";
        /** @enum {unknown} */
        Standing: "RANKED" | "BELOW_FIT" | "DISQUALIFIED" | "CUSTOMER";
        /**
         * WeightLevel
         * @description A weight level of the [scoring settings document]
         *     (/architecture/sql-store.md#scoring-settings-document): `weight_values`, and the `weight` of
         *     an ICP criterion or a question setting. `NONE` keeps a question out of Intent while a
         *     disqualifier still reads it.
         * @enum {string}
         */
        WeightLevel: "HIGH" | "MEDIUM" | "LOW" | "NONE";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_prospects: {
        parameters: {
            query?: {
                page?: number;
                standing?: components["schemas"]["Standing"];
                band?: components["schemas"]["Band"][];
                country_code?: string[];
                industry?: string[];
                q?: string;
                sort?: "priority" | "intent" | "fit" | "name" | "last_refreshed";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_score: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_findings: {
        parameters: {
            query?: {
                service_id?: string;
                question_id?: string;
                status?: components["schemas"]["FindingStatus"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    add_override: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Override"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    revoke_override: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Override"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
