"""Generates requirements/traceability.md from the registers (docs/guidelines/documents/common.md#traceability).

The matrix is derived, never written by hand: requirement -> flows -> entities -> acceptance
criteria, read from the Realises, Flows and Entities columns of requirements/system.md and the
Verifies column of requirements/acceptance.md.

Usage: `uv run --project scripts python scripts/build_traceability.py [--check]`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path, PurePosixPath

from docmd import body_lines, find_tables, heading_anchor, parse_headings, read_bundle

_REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = _REPO_ROOT / "docs"
TARGET = "requirements/traceability.md"
ID_RE = re.compile(r"^`?([A-Z]{1,6}-[A-Z0-9]+(?:-[A-Z0-9]+)*)`?$")
REF_RE = re.compile(r"\b(B-\d{2}|RULE-\d{2}|S-[A-Z]{3}-\d{2}|N-\d{2}|FL-\d{2})\b")
ENTITY_RE = re.compile(r"\]\(/architecture/sql-store\.md#([a-z0-9_-]+)\)")
FL_RE = re.compile(r"^(FL-\d{2}) (.+)$")

HEADER = """---
type: Requirements
title: Traceability matrix
description: Generated from the registers - every system and non-functional requirement with the business rows it realises, the flows and data entities it touches and the acceptance criteria that verify it.
status: draft
tags: [{tags}]
---

# Traceability matrix

Generated by `scripts/build_traceability.py` from the Realises, Flows and Entities columns of
[system requirements](/requirements/system.md) and the Verifies column of
[acceptance criteria](/requirements/acceptance.md). Never edit it by hand: change the register
row and regenerate. The checker fails when this file is stale or when a row below would have an
empty Flows, Entities or Acceptance cell.
"""


def _col(header: list[str], name: str) -> int | None:
    names = [h.strip().lower() for h in header]
    return names.index(name.lower()) if name.lower() in names else None


def _key(ident: str) -> tuple[str, int]:
    prefix, _, num = ident.rpartition("-")
    return prefix, int(num) if num.isdigit() else 0


def render(files: dict[str, str]) -> str:
    lines = {rel: body_lines(text) for rel, text in files.items()}
    flows: dict[str, tuple[str, str, str]] = {}  # id -> (file, anchor, title)
    for rel, ls in lines.items():
        if not rel.startswith("features/") or rel.endswith("index.md"):
            continue
        for h in parse_headings(ls):
            m = FL_RE.match(h.title)
            if m and h.level == 3:
                flows[m.group(1)] = (rel, heading_anchor(h.title), m.group(2))
    feature_slugs = sorted(
        PurePosixPath(r).stem for r in files if r.startswith("features/") and not r.endswith("index.md")
    )

    rows: list[tuple[str, str, list[str], list[str], list[str]]] = []
    for table in find_tables(lines.get("requirements/system.md", [])):
        c = {n: _col(table.header, n) for n in ("Priority", "Realises", "Flows", "Entities")}
        if any(v is None for v in c.values()):
            continue
        for row in table.rows:
            m = ID_RE.match(row[0].strip())
            if not m:
                continue
            fl_cell = row[c["Flows"]]
            fls = [r for r in REF_RE.findall(fl_cell) if r.startswith("FL-")]
            rows.append(
                (
                    m.group(1),
                    row[c["Priority"]].strip(),
                    REF_RE.findall(row[c["Realises"]]),
                    fls or (["all"] if fl_cell.strip().lower() == "all" else []),
                    ENTITY_RE.findall(row[c["Entities"]]),
                )
            )

    verified_by: dict[str, list[str]] = {}
    for table in find_tables(lines.get("requirements/acceptance.md", [])):
        v = _col(table.header, "Verifies")
        if v is None:
            continue
        for row in table.rows:
            m = ID_RE.match(row[0].strip())
            if m and m.group(1).startswith("AC-"):
                for ref in REF_RE.findall(row[v]):
                    verified_by.setdefault(ref, []).append(m.group(1))

    def flow_link(f: str) -> str:
        if f == "all":
            return "all flows"
        rel, anchor, _ = flows.get(f, ("", "", ""))
        return f"[{f}](/{rel}#{anchor})" if rel else f

    def ent_link(e: str) -> str:
        return f"[`{e}`](/architecture/sql-store.md#{e})"

    out = [HEADER.format(tags=", ".join(feature_slugs)).rstrip("\n"), ""]
    out += [
        "## Requirement to acceptance",
        "",
        "| Requirement | Priority | Realises | Flows | Entities | Acceptance |",
        "|---|---|---|---|---|---|",
    ]
    for ident, prio, realises, fls, ents in sorted(rows, key=lambda r: _key(r[0])):
        acs = sorted(set(verified_by.get(ident, [])), key=_key)
        out.append(
            f"| `{ident}` | {prio} | {', '.join(f'`{r}`' for r in realises)} | "
            f"{', '.join(flow_link(f) for f in fls)} | {', '.join(ent_link(e) for e in ents) or 'none'} | "
            f"{', '.join(f'`{a}`' for a in acs)} |"
        )

    out += [
        "",
        "## Flow coverage",
        "",
        "| Flow | Title | Requirements | Acceptance |",
        "|---|---|---|---|",
    ]
    for f in sorted(flows, key=_key):
        reqs = [r[0] for r in rows if f in r[3]]
        acs = sorted({a for r in reqs for a in verified_by.get(r, [])}, key=_key)
        out.append(
            f"| {flow_link(f)} | {flows[f][2]} | {', '.join(f'`{r}`' for r in sorted(reqs, key=_key))} | "
            f"{', '.join(f'`{a}`' for a in acs)} |"
        )

    out += [
        "",
        "## Entity coverage",
        "",
        "| Entity | Requirements |",
        "|---|---|",
    ]
    for e in sorted({e for r in rows for e in r[4]}):
        reqs = sorted({r[0] for r in rows if e in r[4]}, key=_key)
        out.append(f"| {ent_link(e)} | {', '.join(f'`{r}`' for r in reqs)} |")

    out += [
        "",
        "## Business coverage",
        "",
        "| Business row | Realised by | Acceptance |",
        "|---|---|---|",
    ]
    business = sorted({b for r in rows for b in r[2]}, key=_key)
    for b in business:
        reqs = sorted({r[0] for r in rows if b in r[2]}, key=_key)
        acs = sorted({a for r in reqs for a in verified_by.get(r, [])} | set(verified_by.get(b, [])), key=_key)
        out.append(f"| `{b}` | {', '.join(f'`{r}`' for r in reqs)} | {', '.join(f'`{a}`' for a in acs)} |")
    return "\n".join(out) + "\n"


def main() -> None:
    files = read_bundle(str(DOCS))
    content = render(files)
    path = DOCS / TARGET
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if "--check" in sys.argv:
        stale = current != content
        print(f"{TARGET}: {'stale' if stale else 'current'}")
        sys.exit(1 if stale else 0)
    if current != content:
        path.write_text(content, encoding="utf-8")
    print(f"{TARGET} written ({'changed' if current != content else 'unchanged'})")


if __name__ == "__main__":
    main()
