/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description `API-61`: anonymous, `200` when the database check is `OK`, else `503`.
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Health
         * @description [Health](/architecture/interfaces.md#health), the response of `API-61`.
         */
        Health: {
            checks: components["schemas"]["HealthChecks"];
            status: components["schemas"]["HealthStatus"];
        };
        /**
         * HealthCheckStatus
         * @description One dependency's check outcome, of the [Health](/architecture/interfaces.md#health) shape.
         * @enum {string}
         */
        HealthCheckStatus: "OK" | "DOWN" | "NOT_CONFIGURED";
        /**
         * HealthChecks
         * @description The `checks` object of [Health](/architecture/interfaces.md#health).
         */
        HealthChecks: {
            classifier: components["schemas"]["HealthCheckStatus"];
            database: components["schemas"]["HealthCheckStatus"];
            embedder: components["schemas"]["HealthCheckStatus"];
            llm: components["schemas"]["HealthCheckStatus"];
        };
        /**
         * HealthStatus
         * @description The overall `status` of the [Health](/architecture/interfaces.md#health) shape.
         * @enum {string}
         */
        HealthStatus: "OK" | "DEGRADED" | "DOWN";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
